# Generated by Django 6.0.6 on 2026-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructor_feedback',
            field=models.TextField(blank=True, help_text="Instructor's suggestions displayed on the result page", null=True),
        ),
    ]
